//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Fitnes
{
    using System;
    using System.Collections.Generic;
    
    public partial class Maintenance
    {
        public int ID_Maintenance { get; set; }
        public string MaintenanceDate { get; set; }
        public string TypeOfWork { get; set; }
        public int MaintenanceStatus_ID { get; set; }
        public int Technique_ID { get; set; }
    
        public virtual MaintenanceStatus MaintenanceStatus { get; set; }
        public virtual Technique Technique { get; set; }
    }
}
