//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Fitnes
{
    using System;
    using System.Collections.Generic;
    
    public partial class Technique
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Technique()
        {
            this.Maintenance = new HashSet<Maintenance>();
            this.Orders = new HashSet<Orders>();
        }
    
        public int ID_Technique { get; set; }
        public string TechnicianNumber { get; set; }
        public string TechniqueName { get; set; }
        public string TechniqueModel { get; set; }
        public string YearOfManufacture { get; set; }
        public decimal RentalCost { get; set; }
        public int State_ID { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Maintenance> Maintenance { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Orders> Orders { get; set; }
        public virtual States States { get; set; }
    }
}
